apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: node-ts-restfull-api
  title: Node Typescript RestfullApi Backstage
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Basic sets
      required:
        - artifact_name
        - artifact_description
        - owner
        - system
        - azure_docker_registry_scv_connection
        - azure_docker_registry_hostname
        - database_username
        - database_password
        - database_database
        - database_hostname
        - database_hostport
        - application_port
      properties:
        artifact_name:
          title: Artifact Name
          type: string
          pattern: ^[a-z][a-z0-9_]{0,13}[a-z]$
          minLength: 3
          maxLength: 15
        artifact_description:
          title: Artifact Description
          type: string
        owner:
          title: Owner
          type: string
          ui:field: MyGroupsPicker
        system:
          title: System
          type: string
          ui:field: EntityPicker
          ui:options:
            variant: inline
            filter:
              kind: System
            create: false
        azure_docker_registry_scv_connection:
          title: Azure Docker Registry Service Connection
          type: string
        azure_docker_registry_hostname:
          title: Azure Docker Registry Hostname
          type: string
          pattern: ^(?!-)[A-Za-z0-9-]{1,63}(?<!-)(?:\.[A-Za-z0-9-]{1,63})*$
        database_username:
          title: Database Username
          type: string
        database_password:
          title: Database Password
          type: string
        database_database:
          title: Database Name
          type: string
        database_hostname:
          title: Database Hostname
          type: string
        database_hostport:
          title: Database Host Port
          type: integer
          minimum: 1
          maximum: 65535
        application_port:
          title: Application Port
          type: integer
          minimum: 1
          maximum: 65535
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
              - dev.azure.com
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./skeleton
        values:
          artifact_name: "{{ parameters.artifact_name }}"
          artifact_description: "{{ parameters.artifact_description }}"
          owner: "{{ parameters.owner }}"
          system: "{{ parameters.system }}"
          azure_docker_registry_scv_connection: "{{ parameters.azure_docker_registry_scv_connection }}"
          azure_docker_registry_hostname: "{{ parameters.azure_docker_registry_hostname }}"
          database_username: "{{ parameters.database_username }}"
          database_password: "{{ parameters.database_password }}"
          database_database: "{{ parameters.database_database }}"
          database_hostname: "{{ parameters.database_hostname }}"
          database_hostport: "{{ parameters.database_hostport }}"
          application_port: "{{ parameters.application_port }}"


    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

