apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description | dump }}
  annotations:
    github.com/project-slug: ${{ values.github_username + "/" + values.name }}
    backstage.io/techdocs-ref: dir:.
    grafana/dashboard-selector: backstage-grafana-selector
  tags:
    - microservice
    - backend
    - api
    - restfull
    - typescript
    - node
  links:
    - url: https://github.com/${{values.github_username + "/" + values.name}}
      title: Repository
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner | dump }}
  system: ${{ values.system }}
  providesApis:
    - component: ${{ values.name }}
  dependencies:
    - resource: ${{ values.database_hostname }}