apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    backstage.io/techdocs-ref: dir:.
    grafana/dashboard-selector: backstage-grafana-selector
  tags:
    - microservice
    - backend
    - api
    - restfull
    - typescript
    - node
spec:
  type: service
  lifecycle: production
  owner: ${{ values.owner }}
  system: ${{ values.system }}
    - component:${{ values.name }}
  dependencies:
    - resource:${{ values.database_hostname }}